version: '3.2'
services:
  payment-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payment-api
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    links:
      - mysql

  mysql:
    image: mysql:5.7.22
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "payment_api"
      TZ: "America/Sao_Paulo"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10